/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.puncty.lib;

import org.junit.Test;
import static org.junit.Assert.*;

public class RequesterTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Requester req = new Requester("https://example.com");
        assertTrue("new Requester is type of Requester", req.getClass() == Requester.class);
    }
}
