/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.puncty.lib;

import org.junit.Test;

import com.puncty.lib.networking.Requester;

import static org.junit.Assert.*;

import java.io.IOException;

import org.json.JSONException;

public class RequesterTest {
    @Test
    public void someLibraryMethodReturnsTrue() throws IOException, InterruptedException, JSONException {
        var r = new Requester("https://johannespour.de/api");
    }
}
