/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.puncty.lib;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import com.puncty.lib.collections.UserCollection;
import com.puncty.lib.exceptions.BrokenResponse;
import com.puncty.lib.exceptions.RequestFailed;
import com.puncty.lib.exceptions.UserAlreadyExists;
import com.puncty.lib.networking.Requester;



public class SessionTest {
    Requester r = new Requester("http://localhost:3000");

    @Test
    public void register() throws UserAlreadyExists, BrokenResponse, RequestFailed  {
        Session s = Session.register(r, "TestUser", "test@email.com", "Test");
        var uc = new UserCollection(s);
        var me = uc.getMe();

        assertEquals(me.getName(), "TestUser");
        assertEquals(me.getEmail(), "test@email.com");
    }

    public void login() throws RequestFailed, BrokenResponse {
        Session s = Session.login(r, "test@email.com", "Test");
        var uc = new UserCollection(s);

        assertEquals(uc.getMe().getName(), "TestUser");
    }
}
