/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.puncty.lib;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.json.JSONObject;
import org.junit.Test;


public class UserTest {
    @Test
    public void parse() throws Exception {
        var obj = new JSONObject("{\"name\": \"Dude\", \"id\": \"1234\", \"email_address\": \"dude@gmail.com\"}");
        var user = User.fromJSON(obj);
        var other = User.fromJSON(obj);

        assertEquals(user.getName(), "Dude");
        assertEquals(user.getId(), "1234");
        assertEquals(user.getEmail(), "dude@gmail.com");
        assertTrue(user.equals(other));
    }
}
